###
GET http://localhost:3000/sandwhiches

###
GET http://localhost:3000/sandwhiches/3

###
POST http://localhost:3000/sandwhiches
content-type: application/json

{
  "name": "turkey",
  "price": 9,
  "size": "L"
}

###
Patch http://localhost:3000/sandwhiches/6
content-type: application/json

{
  "name": "Roast Beef",
  "price": 10,
  "size": "XL"
}

###
DELETE http://localhost:3000/sandwhiches/8

